"""Added is_delete flag to users

Revision ID: 10cd845d98b
Revises: 178bf6326b0
Create Date: 2015-05-03 14:11:23.695645

"""

# revision identifiers, used by Alembic.
revision = '10cd845d98b'
down_revision = '178bf6326b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    ### end Alembic commands ###
