"""StatusManager

Revision ID: 1662235183e
Revises: ae74e77e32
Create Date: 2015-06-03 15:43:59.908945

"""

# revision identifiers, used by Alembic.
revision = '1662235183e'
down_revision = 'ae74e77e32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
