"""Add Update relationship

Revision ID: 187ab8e646e
Revises: 239ddb2db47
Create Date: 2015-06-07 16:51:15.920347

"""

# revision identifiers, used by Alembic.
revision = '187ab8e646e'
down_revision = '239ddb2db47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
