"""ipam module

Revision ID: 1fe52c86b1f
Revises: 4a3dba55b86
Create Date: 2015-04-29 10:52:28.826000

"""

# revision identifiers, used by Alembic.
revision = '1fe52c86b1f'
down_revision = '4a3dba55b86'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipnetworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipnetwork', postgresql.CIDR(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ipnetwork')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipnetworks')
    ### end Alembic commands ###
