"""New Fields for Status Management

Revision ID: 239ddb2db47
Revises: 65a7a049fd
Create Date: 2015-06-05 15:30:43.715546

"""

# revision identifiers, used by Alembic.
revision = '239ddb2db47'
down_revision = '65a7a049fd'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils 


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('description', sa.String(), nullable=False))
    op.add_column('states', sa.Column('impact', sqlalchemy_utils.types.choice.ChoiceType([
        ('internal', 'BrandMaker Internal Customers'),
        ('external', 'BrandMaker External Customers')
    ]), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'impact')
    op.drop_column('states', 'description')
    ### end Alembic commands ###
