"""New IPAM Settings 2

Revision ID: 24504177b08
Revises: 50e8a213198
Create Date: 2015-04-29 14:01:40.213665

"""

# revision identifiers, used by Alembic.
revision = '24504177b08'
down_revision = '50e8a213198'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
