"""New Sent boolean field

Revision ID: 3c77a66b6ab
Revises: 53c004690f1
Create Date: 2015-06-07 17:56:34.223890

"""

# revision identifiers, used by Alembic.
revision = '3c77a66b6ab'
down_revision = '53c004690f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('sent', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('updates', 'sent')
    ### end Alembic commands ###
