"""New IPAddresses Model

Revision ID: 3d7620e463c
Revises: 5a45812a1cd
Create Date: 2015-05-05 14:07:31.468480

"""

# revision identifiers, used by Alembic.
revision = '3d7620e463c'
down_revision = '5a45812a1cd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipaddresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipaddress', postgresql.INET(), nullable=True),
    sa.Column('ipnetwork_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ipnetwork_id'], ['ipnetworks.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ipaddress')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipaddresses')
    ### end Alembic commands ###
