"""AddPasswordRelationToUsers

Revision ID: 4a3dba55b86
Revises: 21a7ae8d79d
Create Date: 2015-04-20 21:06:48.254457

"""

# revision identifiers, used by Alembic.
revision = '4a3dba55b86'
down_revision = '21a7ae8d79d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
