"""New IPAM Settings

Revision ID: 50e8a213198
Revises: 1fe52c86b1f
Create Date: 2015-04-29 14:00:23.830904

"""

# revision identifiers, used by Alembic.
revision = '50e8a213198'
down_revision = '1fe52c86b1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipnetworks', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.add_column('ipnetworks', sa.Column('updated_by_user_id', sa.Integer(), nullable=True))
    op.drop_constraint('ipnetworks_updated_by_fkey', 'ipnetworks', type_='foreignkey')
    op.drop_constraint('ipnetworks_created_by_fkey', 'ipnetworks', type_='foreignkey')
    op.create_foreign_key(None, 'ipnetworks', 'users', ['updated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'ipnetworks', 'users', ['created_by_user_id'], ['id'])
    op.drop_column('ipnetworks', 'created_by')
    op.drop_column('ipnetworks', 'updated_by')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipnetworks', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ipnetworks', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ipnetworks', type_='foreignkey')
    op.drop_constraint(None, 'ipnetworks', type_='foreignkey')
    op.create_foreign_key('ipnetworks_created_by_fkey', 'ipnetworks', 'users', ['created_by'], ['id'])
    op.create_foreign_key('ipnetworks_updated_by_fkey', 'ipnetworks', 'users', ['updated_by'], ['id'])
    op.drop_column('ipnetworks', 'updated_by_user_id')
    op.drop_column('ipnetworks', 'created_by_user_id')
    ### end Alembic commands ###
