"""Hello

Revision ID: 53c004690f1
Revises: 187ab8e646e
Create Date: 2015-06-07 17:47:01.824164

"""

# revision identifiers, used by Alembic.
revision = '53c004690f1'
down_revision = '187ab8e646e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
