"""change relationship on authtokens and users

Revision ID: 5a45812a1cd
Revises: bbe97b2fb1
Create Date: 2015-05-03 14:19:21.862423

"""

# revision identifiers, used by Alembic.
revision = '5a45812a1cd'
down_revision = 'bbe97b2fb1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
