"""Adding Port Number to XenServer Model

Revision ID: ae74e77e32
Revises: 304bae1f549
Create Date: 2015-05-30 19:54:34.389030

"""

# revision identifiers, used by Alembic.
revision = 'ae74e77e32'
down_revision = '304bae1f549'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xenservers', sa.Column('port', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xenservers', 'port')
    ### end Alembic commands ###
