"""new relationship on authtokens

Revision ID: bbe97b2fb1
Revises: 10cd845d98b
Create Date: 2015-05-03 14:18:02.202090

"""

# revision identifiers, used by Alembic.
revision = 'bbe97b2fb1'
down_revision = '10cd845d98b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
