"""New IPAM Settings 3

Revision ID: ffc7257ce9
Revises: 24504177b08
Create Date: 2015-04-29 14:05:33.225016

"""

# revision identifiers, used by Alembic.
revision = 'ffc7257ce9'
down_revision = '24504177b08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
